tap "arzg/homebrew-vim-strand"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "fd"
brew "fzf"
brew "git"
brew "hugo"
brew "hyperfine"
brew "neovim"
brew "node"
brew "pastel"
brew "ripgrep"
brew "rustup-init"
brew "strand"
brew "tmux", args: ["HEAD"]
brew "tokei"
brew "tree"
brew "yarn"

cask "appcleaner"
cask "discord"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "iterm2-nightly"
cask "lastpass"
cask "syncthing"
cask "zoomus"
