tap "arzg/homebrew-vim-strand"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "hugo"
brew "hyperfine"
brew "neovim"
brew "node"
brew "pastel"
brew "ripgrep"
brew "rustup-init"
brew "strand"
brew "tmux", args: ["HEAD"]
brew "tokei"
brew "tree"
brew "yarn"
brew "youtube-dl"

cask "appcleaner"
cask "discord"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "iterm2"
cask "lastpass"
cask "spotify"
