#!/bin/bash

# shellcheck disable=SC1090
source "$ENV"

PROMPT_COMMAND=__prompt_command
__prompt_command() {
	local exit_status="$?"
	local color="\[\e[1;92m\]"
	if [ "$exit_status" != 0 ]; then
		color="\[\e[1;91m\]"
	fi
	PS1="$color\u@\h \W \[\e[m\]\$ "
}
