#!/usr/bin/env bash

#
# Input
#

# Use a faster key repeat.
defaults write -globalDomain InitialKeyRepeat -float 15
defaults write -globalDomain KeyRepeat -float 2

# Press the Fn key to show Emoji & Symbols.
defaults write com.apple.HIToolbox AppleFnUsageType -int 2

# Use the Light click force.
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad SecondClickThreshold -int 0

#
# Finder
#

# New windows open with the home folder.
defaults write com.apple.Finder NewWindowTarget -string 'PfHm'
defaults write com.apple.Finder NewWindowTargetPath -string 'file://$HOME'

# Don’t show internal hard drives on the Desktop.
defaults write com.apple.Finder ShowHardDrivesOnDesktop -bool false

# Hide Google Drive virtual drive from the Desktop.
defaults write com.apple.Finder ShowExternalHardDrivesOnDesktop -bool false

# Always show file extensions.
defaults write -globalDomain AppleShowAllExtensions -bool true

#
# Dock, Spaces, Mission Control, Exposé
#

# Only show running applications.
defaults write com.apple.Dock static-only -bool true

# Don’t show recently used applications in the Dock.
defaults write com.apple.Dock show-recents -bool false

# Hide indicators for open applications (as all of the items shown in the Dock
# are open).
defaults write com.apple.Dock show-process-indicators -bool false

# Indicate hidden applications by dimming their icons.
defaults write com.apple.Dock showhidden -bool true

# Enable the Exposé trackpad gesture.
defaults write com.apple.Dock showAppExposeGestureEnabled -bool true

# Disable reordering of Spaces based on most recent use.
defaults write com.apple.Dock mru-spaces -bool false

#
# Safari
#

# Don’t automatically open ‘safe’ downloads once they complete.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Clear downloads from the list after they complete successfully.
defaults write com.apple.Safari DownloadsClearingPolicy -int 2

# Enable the Develop menu.
defaults write com.apple.Safari IncludeDevelopMenu -bool true

# Hide the Favourites window that shows when the search field has focus.
defaults write com.apple.Safari ShowFavoritesUnderSmartSearchField -bool false

# Show favicons.
defaults write com.apple.Safari ShowIconsInTabs -bool true

# Disable AutoFill.
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false

# Show a blank page in new tabs and windows.
defaults write com.apple.Safari NewTabBehavior -int 1
defaults write com.apple.Safari NewWindowBehavior -int 1

# Use compact tab layout.
defaults write com.apple.Safari ShowStandaloneTabBar -bool false

# Use DuckDuckGo for searches.
defaults write com.apple.Safari SearchProviderIdentifier -string 'com.duckduckgo'
/usr/libexec/PlistBuddy \
    -c 'set NSPreferredWebServices:NSWebServicesProviderWebSearch:NSDefaultDisplayName DuckDuckGo' \
    ~/Library/Preferences/.GlobalPreferences.plist 
/usr/libexec/PlistBuddy \
    -c "set NSPreferredWebServices:NSWebServicesProviderWebSearch:NSProviderIdentifier 'com.duckduckgo'" \
    ~/Library/Preferences/.GlobalPreferences.plist

#
# iA Writer
#

# Use .md extension for iA Writer files.
defaults write pro.writer.mac 'Document Path Extension' -string 'md'

# Enable smart punctuation in preview.
defaults write pro.writer.mac 'Markdown Smart Punctuation Enabled' -bool true

# Move folders to the top of the Library.
defaults write pro.writer.mac 'Library Pin Folders To Top' -bool true

# Hide everything from the Organizer apart from explicitly-set locations.
defaults write pro.writer.mac 'Organizer Shows Favorites' -bool false
defaults write pro.writer.mac 'Organizer Shows Hashtags' -bool false
defaults write pro.writer.mac 'Organizer Shows Smart Folders' -bool false

# Enable Inspect Element in the web preview.
defaults write pro.writer.mac WebKitDeveloperExtras -bool true

#
# Other
#

# Preserve open windows when quitting applications.
defaults write -globalDomain NSQuitAlwaysKeepsWindows -bool true

# Customise date format in menu bar: <day> <month>  <hours>:<minutes>
defaults write com.apple.menuextra.clock DateFormat -string 'd MMM  HH:mm'

# Only show the ‘normal’ expanded control strip on the touchbar.
defaults write com.apple.touchbar.agent PresentationModeGlobal -string 'fullControlStrip'

# Enable screen zoom with ^Scroll.
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

# Disable smoothing of screen when zoomed in.
defaults write com.apple.universalaccess closeViewSmoothImages -bool false

# Move zoomed-in region continuously with the cursor.
defaults write com.apple.universalaccess closeViewPanningMode -int 0

# Always show proxy icons.
defaults write com.apple.universalaccess showWindowTitlebarIcons -bool true

# Use Monday as the first day of the week.
defaults write -globalDomain AppleFirstWeekday -dict gregorian 2

# Disable artificial thickening of text.
defaults write -globalDomain AppleFontSmoothing -bool false

#
# Restart affected applications
#

# We restart the applications that reopen themselves automatically.
killall Finder
killall Dock
killall SystemUIServer

# We prompt the user to restart all the other applications.
echo 'Changes have been made to the following applications; you may want to restart them.'
echo '    Safari'
echo '    iA Writer'
