#!/usr/bin/env bash

#
# Input
#

# Use a faster key repeat.
defaults write -g InitialKeyRepeat -float 15
defaults write -g KeyRepeat -float 2

# Use the Light click force.
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad SecondClickThreshold -int 0

#
# Finder
#

# New windows open with the home folder.
defaults write com.apple.Finder NewWindowTarget -string "PfHm"
defaults write com.apple.Finder NewWindowTargetPath -string "file://$HOME"

# Don’t show internal hard drives on the Desktop.
defaults write com.apple.Finder ShowHardDrivesOnDesktop -bool false

#
# Dock, Spaces, Mission Control, Exposé
#

# Enable autohide.
defaults write com.apple.Dock autohide -bool true

# Only show running applications.
defaults write com.apple.Dock static-only -bool true

# Don’t show recently used applications in the Dock.
defaults write com.apple.Dock show-recents -bool false

# Hide indicators for open applications (as all of the items shown in the Dock
# are open).
defaults write com.apple.Dock show-process-indicators -bool false

# Enable the Exposé trackpad gesture.
defaults write com.apple.Dock showAppExposeGestureEnabled -bool true

# Disable reordering of Spaces based on most recent use.
defaults write com.apple.Dock mru-spaces -bool false

#
# Safari
#

# Don’t automatically open ‘safe’ downloads once they complete.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Enable the Develop menu.
defaults write com.apple.Safari IncludeDevelopMenu -bool true

# Hide the Favourites window that shows when the search field has focus.
defaults write com.apple.Safari ShowFavoritesUnderSmartSearchField -bool false

# Disable AutoFill.
defaults write com.apple.Safari AutoFillCreditCardData -bool true
defaults write com.apple.Safari AutoFillFromAddressBook -bool true
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool true
defaults write com.apple.Safari AutoFillPasswords -bool true

#
# iA Writer
#

# Use .md extension for iA Writer files.
default write pro.writer.mac "Document Path Extension" -str "md"

#
# Other
#

# Show the percentage of remaining battery in the menu bar.
defaults write com.apple.menuextra.battery ShowPercent -bool true

# Only show the ‘normal’ expanded control strip on the touchbar.
defaults write com.apple.touchbar.agent PresentationModeGlobal -string "fullControlStrip"

# Enable screen zoom with ^Scroll.
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

# Disable smoothing of screen when zoomed in.
defaults write com.apple.universalaccess closeViewSmoothImages -bool false

# Move zoomed-in region continuously with the cursor.
defaults write com.apple.universalaccess closeViewPanningMode -int 0

# Enable the boot chime.
sudo nvram StartupMute=%00

#
# Restart affected applications
#

# We restart the applications that reopen themselves automatically.
killall Finder
killall Dock
killall SystemUIServer

# We prompt the user to restart all the other applications.
echo "Changes have been made to the following applications; you may want to restart them."
echo "    Safari"
