#!/usr/bin/env bash

#
# Input
#

# Use a faster key repeat.
defaults write -g InitialKeyRepeat -float 15
defaults write -g KeyRepeat -float 2

#
# Dock
#

# Enable autohide.
defaults write com.apple.Dock autohide -bool true

# Only show running applications.
defaults write com.apple.Dock static-only -bool true

#
# Safari
#

# Don’t automatically open ‘safe’ downloads once they complete.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Enable the Develop menu.
defaults write com.apple.Safari IncludeDevelopMenu -bool true

#
# Other
#

# Show the percentage of remaining battery in the menu bar.
defaults write com.apple.menuextra.battery ShowPercent -bool true

#
# Restart affected applications
#

# We restart the applications that reopen themselves automatically.
killall Dock
killall SystemUIServer

# We prompt the user to restart all the other applications.
echo "Changes have been made to the following applications; you may want to restart them."
echo "    Safari"
