source "$ENV"

bindkey -e # emacs key bindings
setopt nomatch # error when glob doesn’t match

# completion
autoload compinit && compinit
zstyle ':completion:*' menu select # highlight selected match
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z-_}={A-Za-z_-}' # case and -/_ insensitive

# history
HISTSIZE=100000
SAVEHIST=100000
setopt hist_ignore_all_dups
setopt inc_append_history # append history after each command

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

PROMPT=$'$ '
RPROMPT=$'%{\e[90m%}%1~%{\e[m%}'
