# Aliases

alias vim="$EDITOR"
alias vi="$EDITOR"
alias g=git
alias c=cargo
alias b=brew
alias ls="ls -F"
alias fd="fd --color=never"

# Functions

mkcd() {
	mkdir -p "$1"
	# shellcheck disable=SC2164
	cd "$1"
}

cdsdk() {
	cd "$(xcrun --show-sdk-path)"
}

# Editing

bindkey -e # emacs key bindings
WORDCHARS="${WORDCHARS/\/}" # consider slash a word boundary

# Completion

autoload compinit && compinit
zstyle ':completion:*' menu select # highlight selected match
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z-_}={A-Za-z_-}' # case and -/_ insensitive

# Prompt

PROMPT=$'%% '
