#!/bin/sh

eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$HOME/Code/dotfiles/bin:$HOME/.cargo/bin:$PATH"

export CDPATH=".:..:$HOME/Code:$HOME"

export VISUAL="nvim"
export EDITOR="nvim"

export CLICOLOR="1"
export FZF_DEFAULT_COMMAND="fd --hidden"
export FZF_DEFAULT_OPTS="--color=16,fg+:7,hl:12,hl+:12"
export MANPAGER="nvim +Man!"
export MANWIDTH="72"

export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"

# This disables terminal flow control (whatever that is)
# which frees up C-s and C-q for keybindings.
# We want this because C-s defaults to
# going forward in incremental history search.
stty -ixon

export ENV="$HOME/.shrc"
# shellcheck disable=SC1090
. "$ENV"
