#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export PATH="$HOME/Code/dotfiles/bin:$HOME/.cargo/bin:$HOME/.ghcup/bin:$PATH"

export CDPATH=".:..:$HOME/Code:$HOME"

export VISUAL="vim"
export EDITOR="vim"

export CLICOLOR="1"
export FZF_DEFAULT_COMMAND="fd --hidden"
export MANPAGER="col -b | vim --not-a-term -c 'set filetype=man nomodified' - "
export MANWIDTH="72"

if [ "$(uname)" = "Darwin" ]; then
	export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
fi

# This disables terminal flow control (whatever that is)
# which frees up C-s and C-q for keybindings.
# We want this because C-s defaults to
# going forward in incremental history search.
stty -ixon

export ENV="$HOME/.shrc"
# shellcheck disable=SC1090
. "$ENV"
