#!/bin/sh

alias vim=nvim
alias vi=nvim
alias g=git
alias c=cargo
alias b=brew
alias m="make -j10"
alias ls="ls -F"

mkcd() {
	mkdir -p "$1"
	# shellcheck disable=SC2164
	cd "$1"
}

makeunirepo() {
	git config user.email u7653557@anu.edu.au
	git config user.signingkey "key::ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEUy5Hd+s+KeEnAJhRX6RYQp8AL4mwaElQM87+dJRVEqTfWnhdDbWw8ECKe+zbpUlxlpr6GXlZ05X5TPzpyDUXI="
}

export PS1
PS1="$(ps -p $$ -o comm=)$ "
