filetype plugin indent on
syntax on

set autoindent
set autoread
set breakindent
set clipboard^=unnamed
set colorcolumn=+1
set directory=$HOME/.vim/swapfiles//
set grepformat^=%f:%l:%c:%m
set grepprg=rg\ --vimgrep\ --ignore-case
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set list
set modelines=5 " the system vimrc on macOS overrides the Vim default of 5 and sets this to 0
set numberwidth=5
set path=.,,src/**
set shortmess-=S " search result counter
set smartcase
set splitbelow
set splitright
set ttimeoutlen=0 " remove delay when pressing <Esc> to exit command-line mode
set wildignore=*/out/*
set wildmenu

let &statusline = " %f %r%m%y%=%4l/%-4L %4c %4v "

let &listchars = "tab:» ,nbsp:•,trail:•"
let &showbreak = "››› "

" Plugins

let g:lion_squeeze_spaces = 1

let g:rustfmt_autosave = 1

let g:mucomplete#chains = {
			\ 'vim': ['cmd', 'c-n'],
			\ 'default': ['omni', 'c-n']
			\ }

let g:c_syntax_for_h = 1
let g:cpp_simple_highlight = 1

" Mappings

inoremap (<CR> (<CR>)<Esc>O
inoremap {<CR> {<CR>}<Esc>O

nnoremap <expr> k v:count == 0 ? 'gk' : 'k'
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'

vnoremap < <gv
vnoremap > >gv

command! -nargs=+ -complete=file_in_path -bar Grep silent! lgrep! <args> | redraw!

nnoremap ,f :find<Space>
nnoremap ,g :Grep<Space>
nnoremap ,b :ls<CR>:b<Space>

nnoremap ,s :split<CR>
nnoremap ,v :vsplit<CR>
nnoremap ,t :tabnew<CR>
nnoremap ,c :close<CR>
nnoremap ,o :only<CR>

" Autocmds

function! SourcePersonalVimrc()
	let l:path = expand("%:p:h") . "/.personalvimrc"
	if filereadable(l:path)
		execute "source " . l:path
	endif
endfunction

augroup vimrc
	autocmd!

	autocmd BufRead * call SourcePersonalVimrc()
	autocmd BufReadPost * if &textwidth == 0 | setlocal textwidth=80 | endif

	autocmd BufWritePost *.html,*.css,*.scss,*.md execute "silent! !prettier -w %" | redraw!
	autocmd BufRead *.html,*.css,*.scss,*.md setlocal softtabstop=2 shiftwidth=2 expandtab

	autocmd BufWritePost *.c,*.h silent make! | redraw!

	autocmd ColorScheme * hi link Searchlight IncSearch
augroup END

" Color scheme

" Fix background color in Kitty
" https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim
let &t_ut=''

set termguicolors
colorscheme smyck-custom
