filetype plugin indent on
syntax on

set autoindent
set autoread
set clipboard^=unnamed
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set list
set listchars=tab:\ \ ,nbsp:•,trail:•
set numberwidth=5
set smartcase
set splitbelow
set splitright
set ttimeoutlen=0 " remove delay when pressing <Esc> to exit command-line mode
set wildmenu

let &statusline = " %f %r%m%=%3l %3c/%-3v "

" Plugins

let g:lion_squeeze_spaces = 1

set runtimepath+=/opt/homebrew/opt/fzf
let g:fzf_layout = { 'down': '~40%' }

let g:rustfmt_autosave = 1

let g:mucomplete#chains = {
			\ 'vim': ['cmd', 'c-n'],
			\ 'default': ['omni', 'c-n']
			\ }

let g:c_syntax_for_h = 1
let g:cpp_simple_highlight = 1

" Mappings

inoremap (<CR> (<CR>)<Esc>O
inoremap {<CR> {<CR>}<Esc>O

nnoremap <expr> k v:count == 0 ? 'gk' : 'k'
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'

vnoremap < <gv
vnoremap > >gv

nnoremap ,b :Buffers<CR>
nnoremap ,c :close<CR>
nnoremap ,f :Files<CR>
nnoremap ,g :Rg<CR>
nnoremap ,o :only<CR>
nnoremap ,s :split<CR>
nnoremap ,v :vsplit<CR>

" Autocmds

augroup vimrc
	autocmd!

	autocmd BufWritePost *.html,*.css,*.scss,*.md silent! !prettier -w %
	autocmd BufRead *.html,*.css,*.scss,*.md set sts=2 sw=2 et

	autocmd ColorScheme * hi link Searchlight IncSearch
	autocmd ColorScheme lucius hi Search ctermfg=236 ctermbg=230 cterm=NONE
augroup END

" Color scheme

colorscheme lucius
LuciusDarkHighContrast
